services:
  - type: web
    name: seera-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegrambot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromSecret: telegram_token
      - key: HF_API_KEY
        fromSecret: hf_api_key